### ISSUE TITLE
dbplyr compatibility?

### ISSUE THREAD

**Issue by krlmlr** [echasnovski/keyholder#4]
What would it take to add support for dbplyr tables to keyholder?

``` r
library(keyholder)
#> 
#> Attaching package: 'keyholder'
#> The following object is masked from 'package:stats':
#> 
#>     filter
library(tidyverse)

data <- tibble(a = 1:3)
key_by(data, a)
#> # A keyed object. Keys: a 
#> # A tibble: 3 x 1
#>       a
#>   <int>
#> 1     1
#> 2     2
#> 3     3

data <- dbplyr::memdb_frame(a = 1:3)
key_by(data, a)
#> Error in logical(nrow(.tbl)): vector size cannot be NA
```

<sup>Created on 2020-04-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by echasnovski** [comment]
Hmm... This is certainly challenging, but might be doable.
May I ask what is a use case in your 'dm' package? I am just afraid that my unfortunate choice of package name might mislead you in its purpose. It is not really about "keys" in database sense. The common use cases are to track rows of data without asking user to modify it and to backup and restore information about rows.

**Comment by krlmlr** [comment]
Ideally all tables in a dm would already know their keys. Currently they are stored in a redundant data structure. I see the following potential overlap with keyholder:

- the data structure: holding multiple (named?) keys consisting of one or more columns, consistent with the data
    - each table can have primary and foreign keys
    - each key consists of multiple columns (without renaming any of them)
    - for re-identification, each key should have a name that never changes unless explicitly overridden
    - primary keys uniquely identify rows
- updating (renaming/removing) keys after dplyr operations
    - rename: key column is renamed, key name is kept unchanged
    - mutate: destroys key property unless specified otherwise
    - summarize: only keys that are a subset of the grouping columns are retained
    - ...

Do you think keys in the database sense, as described above, are within the scope of this package?

Maybe we can start from scratch, with a `keyed_tbl` structure that implements everything in a manner consistent with all dplyr backends, so that `keyed_df` can build on top and implement all the extra operations like restore?

**Comment by echasnovski** [comment]
Data structure: there are some similarities, except maybe uniqueness of primary key. Functions in 'dplyr': seems like these are different scopes.

This package was initially intended as a simple helper for ['ruler'](https://github.com/echasnovski/ruler) package. Given user defined function (which uses only 'dplyr' verbs), I needed a way to track which rows of original data frame correspond to its output. Its core intended functionality is placed in [this file](https://github.com/echasnovski/keyholder/blob/master/R/keyed-df-one-tbl.R) and [these two functions](https://github.com/echasnovski/keyholder/blob/6c1d4981a86221bd31b4acb470c6fba79439dc85/R/keyed-df-one-tbl.R#L110-L131) in particular:

- If verb doesn't change row order (`mutate()`, `transmute()`, `select()`, etc.), "keys" are propagated untouched.
- If verb changes row order (`arrange()`, `filter()`, etc.) "keys" are reordered in the same way as input data frame (by creating "row identifier" column before function application and using its values after).
- If rows collapse (`summarise()`, `distinct()`, `do()`), keys are dropped.

Any extra functionality (many keys, `key_by()`, etc.) was added because it seemed easy to implement, may be helpful to others, and I was curious to do it.

Better name for this package would be "rowtracker", but I came up with it well after CRAN submission.

Some code example of core functionality:

``` r
library(keyholder, warn.conflicts = FALSE, quietly = TRUE)
library(dplyr, warn.conflicts = FALSE, quietly = TRUE)

my_fun <- . %>% transmute(is_odd = a %% 2 == 1) %>% slice(c(5, 10, 2))

data <- tibble(a = 1:10)

# Intended use by user. Output has computation results of rows 5, 10, and 2 of
# the original data
data %>% my_fun()
#> # A tibble: 3 x 1
#>   is_odd
#>   <lgl> 
#> 1 TRUE  
#> 2 FALSE 
#> 3 FALSE

# To identify row numbers in output without almost any information about
# `my_fun()`, we need to add "key" with row number, apply user function, and get
# which subset of original "key" is left
data %>% use_id() %>% my_fun() %>% keys()
#> # A tibble: 3 x 1
#>     .id
#>   <int>
#> 1     5
#> 2    10
#> 3     2
```

<sup>Created on 2020-04-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by krlmlr** [comment]
My understanding of the core functionality: the keys are hidden columns that remain in existence no matter what the user does to the data, to track provenance of each row.

It's a bit ironic that the rest seems to be more useful for dm ;-)

I wonder if the following approach will also support the core functionality:

- keys are not copied, we only store the names of the key columns
- we track keys in dplyr and slicing operations, like dm currently does
    - if key columns or key properties are lost, the user gets an error, a warning, a message or a signal, depending on the initial choice when keying
- matching the data with the original becomes a simple join operation

An example for tracking keys in a summary operation (the third drawing is a bit odd, https://github.com/krlmlr/dm/issues/37):

``` r
library(dm)

dm_nycflights13() %>% 
  dm_draw()
```

![](https://i.imgur.com/opjnjjB.png)

``` r

dm_nycflights13() %>% 
  dm_zoom_to(flights) %>% 
  group_by(carrier, origin) %>% 
  summarize(n = n()) %>% 
  ungroup() %>%
  dm_insert_zoomed("n_flights") %>% 
  dm_draw()
```

![](https://i.imgur.com/tyhWrHA.png)

``` r

dm_nycflights13() %>% 
  dm_zoom_to(planes) %>% 
  mutate(age = 2020 - year) %>% 
  dm_insert_zoomed("planes_with_year") %>% 
  dm_draw()
```

![](https://i.imgur.com/ECweQ7F.png)

<sup>Created on 2020-04-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by echasnovski** [comment]
I still can't wrap my head around how these two approach can come together. Some more thoughts:

- Currently "keys" is a whole separate tibble, rows of which update in sync with row updates of original table. There can be, and in most situations there are, columns in "keys" which are not present in base table (core use case - tibble with 1 column of row identifiers which is not present in base). So, in database terminology, 'keyholder' keyed table is two tables with complete one-to-one synchronized relation between them. In a sense, it is a mini-dm with 2 tables :)
- Summarizing operations seems to have need to drop "keys". For example, is there a reasonable one-to-one relation between sum of a column in base table and rows of "keys"? Empty table with same columns might be an answer, but I am not sure how reasonable this is.

I'll try to think about this more thoroughly for a couple of days and get back to you.

**Comment by echasnovski** [comment]
Sadly, currently I can't see a good way to incorporate "database-like key" functionality into current package framework.
Thank you for the suggestion, @krlmlr! I'll leave this open as a reminder to challenge this again some time in the future.

**Comment by echasnovski** [comment]
Unfortunately, I don't think I will be working on this.
